# frozen_string_literal: true

# Compose two exact feasibility channels at the real 19.32 um pitch.

require "fileutils"

include RBA

root = File.expand_path("../..", __dir__)
build = File.join(root, "build/v3/channel_architecture_guard_pair")
input = File.join(root, "build/v3/channel_architecture_feasibility/v3_channel_architecture_feasibility.gds")
output = File.join(build, "v3_channel_architecture_guard_pair.gds")
check_tcl = File.join(build, "check.tcl")
source_top = "v3_channel_architecture_feasibility"
pair_top = "v3_channel_architecture_guard_pair"
channel_pitch_um = 19.32

FileUtils.mkdir_p(build)
layout = Layout.new
layout.read(input)
source = layout.cell(source_top)
raise "missing source top #{source_top}" if source.nil?

old_pair = layout.cell(pair_top)
layout.delete_cell(old_pair.cell_index) unless old_pair.nil?
pair = layout.create_cell(pair_top)
pitch_dbu = (channel_pitch_um / layout.dbu).round
pair.insert(CellInstArray.new(source.cell_index, Trans.new(0, 0)))
pair.insert(CellInstArray.new(source.cell_index, Trans.new(pitch_dbu, 0)))
layout.write(output)

tcl = <<~TCL
  # Generated by v3/tools/compose_channel_architecture_guard_pair.rb; do not edit.
  set PROJECT_ROOT [file normalize [pwd]]
  set WORKDIR [file join $PROJECT_ROOT build v3 channel_architecture_guard_pair]
  set TOP #{pair_top}
  cd $WORKDIR
  gds read [file join $WORKDIR #{File.basename(output)}]
  load $TOP
  select top cell
  expand
  flatten $TOP
  load $TOP
  select top cell
  drc euclidean on
  drc style drc(full)
  drc check
  set drc_count [drc list count total]
  puts "V3_CHANNEL_GUARD_PAIR_DRC_COUNT=$drc_count"
  if {$drc_count != 0} {
      feedback save [file join $WORKDIR drc_feedback.txt]
      error "adjacent-channel guard pilot has DRC errors"
  }
  extract unique notopports
  extract do local
  extract all
  set extraction_feedback [feedback count]
  puts "V3_CHANNEL_GUARD_PAIR_EXTRACTION_FEEDBACK_COUNT=$extraction_feedback"
  if {$extraction_feedback != 0} {
      feedback save [file join $WORKDIR extraction_feedback.txt]
      error "adjacent-channel guard extraction produced feedback"
  }
  ext2spice lvs
  ext2spice hierarchy off
  ext2spice extresist off
  ext2spice cthresh 1e99
  ext2spice rthresh infinite
  ext2spice -o [file join $WORKDIR ${TOP}_flat.spice] ${TOP}.ext
  gds compress 0
  gds write [file join $WORKDIR ${TOP}_checked.gds]
  set gds_feedback [feedback count]
  puts "V3_CHANNEL_GUARD_PAIR_GDS_FEEDBACK_COUNT=$gds_feedback"
  set summary [open [file join $WORKDIR physical_markers.txt] w]
  puts $summary "V3_CHANNEL_GUARD_PAIR_DRC_COUNT=$drc_count"
  puts $summary "V3_CHANNEL_GUARD_PAIR_EXTRACTION_FEEDBACK_COUNT=$extraction_feedback"
  puts $summary "V3_CHANNEL_GUARD_PAIR_GDS_FEEDBACK_COUNT=$gds_feedback"
  close $summary
  quit -noprompt
TCL
File.write(check_tcl, tcl)

bbox = pair.bbox
values = [bbox.left, bbox.bottom, bbox.right, bbox.top].map { |value| value * layout.dbu }
puts output
puts check_tcl
puts "pair_bbox_um=#{values.inspect}"
puts "channel_pitch_um=#{channel_pitch_um}"
