#!/usr/bin/env python3
"""Generate the first P-side output-capacitance compensation PCell block."""

from __future__ import annotations

from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUTPUT = ROOT / "build/v3/output_compensation_cap_block/build.tcl"
TOP = "v3_output_compensation_cap_block"
SIZE_UM = 4.20
CENTER = [65.0, 104.0]


def fmt(value: float) -> str:
    return f"{value:.6f}".rstrip("0").rstrip(".")


def build() -> str:
    anchor = [CENTER[0] - (SIZE_UM / 2.0 + 1.08), CENTER[1] - (SIZE_UM / 2.0 + 0.20)]
    c1 = [CENTER[0] - 0.88, CENTER[1]]
    c2 = [CENTER[0] + SIZE_UM / 2.0 + 0.82, CENTER[1]]
    return f"""# Generated by v3/tools/generate_output_compensation_cap_block.py; do not edit.
set PROJECT_ROOT [file normalize [pwd]]
set WORKDIR [file join $PROJECT_ROOT build v3 output_compensation_cap_block]
set SOURCE_TOP v3_output_compensation_cap_source
set TOP {TOP}
file mkdir $WORKDIR
cd $WORKDIR
foreach stale [glob -nocomplain [file join $WORKDIR ${{SOURCE_TOP}}*] [file join $WORKDIR ${{TOP}}*]] {{ file delete -force $stale }}
catch {{cellname delete $SOURCE_TOP}}
catch {{cellname delete $TOP}}
load $SOURCE_TOP -silent
box {fmt(anchor[0])}um {fmt(anchor[1])}um {fmt(anchor[0])}um {fmt(anchor[1])}um
magic::gencell sky130::sky130_fd_pr__cap_mim_m3_1 XOUTCOMP w {fmt(SIZE_UM)} l {fmt(SIZE_UM)} nx 1 ny 1 doports 0
catch {{cellname delete {{(UNNAMED)}}}}
save $SOURCE_TOP.mag
writeall force
select top cell
expand
flatten $TOP
load $TOP
select top cell
box {fmt(c1[0]-0.20)}um {fmt(c1[1]-0.20)}um {fmt(c1[0]+0.20)}um {fmt(c1[1]+0.20)}um
label output_comp center metal4
port make
port class bidirectional
port use signal
port connections n s e w
box {fmt(c2[0]-0.20)}um {fmt(c2[1]-0.20)}um {fmt(c2[0]+0.20)}um {fmt(c2[1]+0.20)}um
label VGND center metal3
port make
port class input
port use ground
port connections n s e w
save $TOP.mag
writeall force
select top cell
expand
drc euclidean on
drc style drc(full)
drc check
set drc_count [drc list count total]
puts "V3_OUTPUT_COMP_CAP_DRC_COUNT=$drc_count"
if {{$drc_count != 0}} {{
    feedback save [file join $WORKDIR drc_feedback.txt]
    error "output compensation capacitor has DRC errors"
}}
extract unique notopports
extract do local
extract all
set extraction_feedback [feedback count]
puts "V3_OUTPUT_COMP_CAP_EXTRACTION_FEEDBACK_COUNT=$extraction_feedback"
if {{$extraction_feedback != 0}} {{
    feedback save [file join $WORKDIR extraction_feedback.txt]
    error "output compensation capacitor extraction produced feedback"
}}
ext2spice lvs
ext2spice hierarchy off
ext2spice extresist off
ext2spice cthresh 1e99
ext2spice rthresh infinite
ext2spice -o [file join $WORKDIR ${{TOP}}_flat.spice] ${{TOP}}.ext
gds compress 0
gds write [file join $WORKDIR ${{TOP}}.gds]
puts "V3_OUTPUT_COMP_CAP_GDS_FEEDBACK_COUNT=[feedback count]"
quit -noprompt
"""


def main() -> None:
    DEFAULT_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    DEFAULT_OUTPUT.write_text(build(), encoding="utf-8")
    print(DEFAULT_OUTPUT)


if __name__ == "__main__":
    main()
