#!/usr/bin/env python3
"""Generate the reusable, closed VCM support block without obsolete top routing."""

from __future__ import annotations

import copy
import json
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "v3/tools"))

from generate_vcm_support_pilot import build_tcl  # noqa: E402


MANIFEST = ROOT / "v3/layout/shared_support_placement.json"
CATALOG = ROOT / "v3/layout/shared_support_pcell_catalog.json"
DEFAULT_OUTPUT = ROOT / "build/v3/vcm_support_block/build.tcl"


def build() -> str:
    data = copy.deepcopy(json.loads(MANIFEST.read_text(encoding="utf-8")))
    catalog = json.loads(CATALOG.read_text(encoding="utf-8"))
    feed = data["vcm"]["feed"]
    obsolete_end = [113.62, 90.0]
    if feed["segments"][-1]["to"] != obsolete_end:
        raise RuntimeError("obsolete VCM pilot feed changed; review the block extraction")
    feed["segments"] = feed["segments"][:-1]
    text = build_tcl(data, catalog)
    text = text.replace(
        "Generated by v3/tools/generate_vcm_support_pilot.py",
        "Generated by v3/tools/generate_vcm_support_block.py",
    )
    text = text.replace(
        "set WORKDIR [file join $PROJECT_ROOT build v3 vcm_support_pilot]",
        "set WORKDIR [file join $PROJECT_ROOT build v3 vcm_support_block]",
    )
    text = text.replace("set TOP v3_vcm_support_pilot", "set TOP v3_vcm_support_block")
    text = text.replace("V3_VCM_SUPPORT_", "V3_VCM_SUPPORT_BLOCK_")
    text = text.replace("label vcm center metal4", "label ref center metal4")
    return text


def main() -> None:
    DEFAULT_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    DEFAULT_OUTPUT.write_text(build(), encoding="utf-8")
    print(DEFAULT_OUTPUT)


if __name__ == "__main__":
    main()
