#!/usr/bin/env python3
"""Generate the Magic build script for the V3 tail-reference/bias-tree pilot."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[2]
MANIFEST = ROOT / "v3" / "layout" / "bias_distribution.json"
DEFAULT_OUTPUT = ROOT / "build" / "v3" / "tail_reference_pilot" / "build.tcl"


def fmt(value: float) -> str:
    return f"{value:.6f}".rstrip("0").rstrip(".")


def paint_rect(layer: str, bbox: list[float]) -> list[str]:
    return [
        f"box {fmt(bbox[0])}um {fmt(bbox[1])}um {fmt(bbox[2])}um {fmt(bbox[3])}um",
        f"paint {layer}",
    ]


def contact(layer: str, point: list[float], size: float) -> list[str]:
    half = size / 2.0
    return paint_rect(layer, [point[0] - half, point[1] - half, point[0] + half, point[1] + half])


def route_rect(item: dict[str, Any]) -> list[float]:
    x0, y0 = item["from"]
    x1, y1 = item["to"]
    half = item["width_um"] / 2.0
    if x0 == x1:
        return [x0 - half, min(y0, y1) - half, x0 + half, max(y0, y1) + half]
    if y0 == y1:
        return [min(x0, x1) - half, y0 - half, max(x0, x1) + half, y0 + half]
    raise ValueError(f"non-Manhattan segment: {item}")


def build_tcl(data: dict[str, Any]) -> str:
    reference = data["reference"]
    center = reference["center_um"]
    anchor = reference["gencell_anchor_um"]
    parameters = reference["parameters"]
    access = reference["terminal_access"]
    commands: list[str] = []
    for access_class in (
        "drain_via1_centers_um",
        "gate_via1_centers_um",
        "source_via1_centers_um",
        "body_via1_centers_um",
    ):
        for point in access[access_class]:
            # The stock PCell is DRC-clean and ends at its Metal-1 terminals;
            # the parent-level Via-1 below is our integration geometry.  Its
            # 0.15 um cut needs 0.055 um M1 enclosure on every edge and
            # 0.085 um on two adjacent edges (SKY130 via.4a/via.5a), which is
            # wider than the diffusion-finger terminal alone.  Paint the
            # legal 0.32 um local landing before adding our Via-1 cut.
            commands.extend(contact("metal1", point, access["via1_box_um"][0]))
            commands.extend(contact("via1", point, access["via1_box_um"][0]))
    commands.extend(paint_rect("metal2", reference["straps"]["vbias_ref"]["bbox_um"]))
    commands.extend(paint_rect("metal2", reference["straps"]["VGND"]["bbox_um"]))
    for item in data["common_route"]["segments"]:
        commands.extend(paint_rect(item["layer"], route_rect(item)))
    for point in (data["common_route"]["start"], data["common_route"]["root"]):
        commands.extend(contact("metal3", point, data["common_route"]["intermediate_metal3_landing_um"][0]))
        commands.extend(contact("via2", point, 0.40))
        commands.extend(contact("via3", point, 0.40))
    for item in data["bias_tree"]["segments"]:
        commands.extend(paint_rect(item["layer"], route_rect(item)))
    command_text = "\n".join(commands)

    return f"""# Generated by v3/tools/generate_tail_reference_pilot.py; do not edit.
set PROJECT_ROOT [file normalize [pwd]]
set WORKDIR [file join $PROJECT_ROOT build v3 tail_reference_pilot]
set SOURCE_TOP v3_tail_reference_source
set TOP v3_tail_reference_pilot
file mkdir $WORKDIR
cd $WORKDIR

foreach stale [glob -nocomplain [file join $WORKDIR ${{SOURCE_TOP}}*] [file join $WORKDIR ${{TOP}}*]] {{
    file delete -force $stale
}}
catch {{cellname delete $SOURCE_TOP}}
catch {{cellname delete $TOP}}
load $SOURCE_TOP -silent
box {fmt(anchor[0])}um {fmt(anchor[1])}um {fmt(anchor[0])}um {fmt(anchor[1])}um
magic::gencell sky130::sky130_fd_pr__nfet_01v8 XREF \
    w {fmt(parameters['finger_width_um'])} l {fmt(parameters['length_um'])} \
    nf {parameters['fingers']} m 1 guard 1 conn_gates 1 full_metal 1 \
    viagb {parameters['body_metal_coverage_percent']} doports 0
save $SOURCE_TOP.mag
writeall force

# Flatten before strapping.  The even-finger PCell does not expose its outer
# D8 diffusion as a child port, so a hierarchical parent wire could look
# connected while extraction leaves that diffusion floating.
select top cell
expand
flatten $TOP
load $TOP
select top cell

{command_text}

box 193.80um 52.00um 194.20um 52.40um
label vbias_ref center metal2
port make
port class bidirectional
port use signal
port connections n s e w
box 193.80um 43.00um 194.20um 43.40um
label VGND center metal2
port make
port class bidirectional
port use ground
port connections n s e w

save $TOP.mag
writeall force
select top cell
expand
drc euclidean on
drc style drc(full)
drc check
set drc_count [drc list count total]
puts "V3_TAIL_REFERENCE_DRC_COUNT=$drc_count"
if {{$drc_count != 0}} {{
    feedback save [file join $WORKDIR drc_feedback.txt]
    error "tail-reference pilot has DRC errors"
}}

extract unique notopports
extract do local
extract all
set extraction_feedback [feedback count]
puts "V3_TAIL_REFERENCE_EXTRACTION_FEEDBACK_COUNT=$extraction_feedback"
if {{$extraction_feedback != 0}} {{
    feedback save [file join $WORKDIR extraction_feedback.txt]
    error "tail-reference pilot extraction produced feedback"
}}
ext2spice lvs
ext2spice hierarchy off
ext2spice extresist off
ext2spice cthresh 1e99
ext2spice rthresh infinite
ext2spice -o [file join $WORKDIR ${{TOP}}_flat.spice] ${{TOP}}.ext
gds write [file join $WORKDIR ${{TOP}}.gds]
puts "V3_TAIL_REFERENCE_GDS_FEEDBACK_COUNT=[feedback count]"
quit -noprompt
"""


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", type=Path, default=MANIFEST)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    data = json.loads(args.manifest.read_text(encoding="utf-8"))
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(build_tcl(data), encoding="utf-8")
    print(args.output)


if __name__ == "__main__":
    main()
