#!/usr/bin/env python3
"""Generate the exact one-unit V3 late-promotion routing pilot."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

import generate_vector_unit_pilot as base


ROOT = Path(__file__).resolve().parents[2]
MANIFEST = ROOT / "v3/layout/vector_unit_late_promotion.json"
CATALOG = ROOT / "v3/layout/channel_pcell_catalog.json"
DEFAULT_OUTPUT = ROOT / "build/v3/vector_unit_late_promotion/build.tcl"
TOP = "v3_vector_unit_late_promotion"


def build_tcl(data: dict[str, Any], catalog: dict[str, Any]) -> str:
    instances = "\n".join(base.pcell_command(item, catalog) for item in data["devices"])
    commands: list[str] = []

    for item in data["devices"]:
        for terminal_name in ("D", "S"):
            commands.extend(base.device_contact_stack(item, terminal_name))

    # Switch gates retain their proven M1 escape and M3 landing.  SIG, REF,
    # and VBIAS deliberately receive no in-place Via-1/2/3 ladder.
    for promotion in data["switch_gate_promotions"]:
        point = base.shifted(promotion["point"])
        commands.extend(base.contact_stack(*point))
        commands.extend(base.compact_via2_tall_stack(*point))
    for segments in data["routes"].values():
        commands.extend(base.route(item) for item in segments)
    for point in ([1.08, 11.465], [1.78, 9.435], [2.20, 2.975]):
        commands.extend(base.compact_via2_stack(*base.shifted(point)))

    tile = data["tile_bbox"]
    guard = [
        base.ORIGIN[0] + tile[0] - 0.8,
        base.ORIGIN[1] + tile[1] - 0.8,
        base.ORIGIN[0] + tile[2] + 0.8,
        base.ORIGIN[1] + tile[3] + 0.8,
    ]
    guard_join = [
        base.ORIGIN[0] + data["boundary_ports"]["VGND"]["point"][0], guard[1]
    ]
    ground_boundary = base.shifted(data["boundary_ports"]["VGND"]["point"])
    commands.append(base.wire_v(
        "metal3", ground_boundary[0], guard_join[1], ground_boundary[1], 0.40,
    ))
    commands.extend(base.li_to_m1_stack(*guard_join))
    commands.extend(base.contact_stack(*guard_join))
    commands.extend(base.via2_stack(*guard_join))

    labels: list[str] = []
    for name, port in data["boundary_ports"].items():
        x, y = base.shifted(port["point"])
        layer = port["layer"]
        labels.append(
            f"box {base.fmt(x - 0.20)}um {base.fmt(y - 0.20)}um "
            f"{base.fmt(x + 0.20)}um {base.fmt(y + 0.20)}um\n"
            f"label {name} center {layer}\nport make\n"
            f"port class {'output' if name in ('outp', 'outn') else 'input'}\n"
            f"port use {'ground' if name == 'VGND' else 'signal'}\n"
            "port connections n s e w"
        )

    return f"""# Generated by v3/tools/generate_vector_unit_late_promotion_pilot.py; do not edit.
set PROJECT_ROOT [file normalize [pwd]]
set WORKDIR [file join $PROJECT_ROOT build v3 vector_unit_late_promotion]
set SOURCE_TOP v3_vector_unit_late_source
set TOP {TOP}
file mkdir $WORKDIR
cd $WORKDIR
foreach stale [glob -nocomplain [file join $WORKDIR ${{SOURCE_TOP}}*] [file join $WORKDIR ${{TOP}}*]] {{
    file delete -force $stale
}}
catch {{cellname delete $SOURCE_TOP}}
catch {{cellname delete $TOP}}
load $SOURCE_TOP -silent

{instances}

catch {{cellname delete {{(UNNAMED)}}}}
save $SOURCE_TOP.mag
writeall force
select top cell
expand
flatten $TOP
load $TOP
select top cell

proc paint_rect {{layer x1 y1 x2 y2}} {{
    box ${{x1}}um ${{y1}}um ${{x2}}um ${{y2}}um
    paint $layer
}}

box {base.fmt(guard[0])}um {base.fmt(guard[1])}um {base.fmt(guard[2])}um {base.fmt(guard[3])}um
sky130::subconn_guard_draw

{chr(10).join(commands)}

box {base.fmt(guard_join[0] - 0.08)}um {base.fmt(guard_join[1] - 0.08)}um {base.fmt(guard_join[0] + 0.08)}um {base.fmt(guard_join[1] + 0.08)}um
label VGND center locali

{chr(10).join(labels)}

save $TOP.mag
writeall force
select top cell
expand
drc euclidean on
drc style drc(full)
drc check
set drc_count [drc list count total]
puts "V3_VECTOR_UNIT_DRC_COUNT=$drc_count"
if {{$drc_count != 0}} {{
    feedback save [file join $WORKDIR drc_feedback.txt]
    error "late-promotion vector-unit pilot has DRC errors"
}}
extract unique notopports
extract do local
extract all
set extraction_feedback [feedback count]
puts "V3_VECTOR_UNIT_EXTRACTION_FEEDBACK_COUNT=$extraction_feedback"
if {{$extraction_feedback != 0}} {{
    feedback save [file join $WORKDIR extraction_feedback.txt]
    error "late-promotion vector-unit extraction produced feedback"
}}
ext2spice lvs
ext2spice hierarchy off
ext2spice extresist off
ext2spice cthresh 1e99
ext2spice rthresh infinite
ext2spice -o [file join $WORKDIR ${{TOP}}_flat.spice] ${{TOP}}.ext
gds compress 0
gds write [file join $WORKDIR ${{TOP}}.gds]
puts "V3_VECTOR_UNIT_GDS_FEEDBACK_COUNT=[feedback count]"
quit -noprompt
"""


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", type=Path, default=MANIFEST)
    parser.add_argument("--catalog", type=Path, default=CATALOG)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    data = json.loads(args.manifest.read_text(encoding="utf-8"))
    catalog = json.loads(args.catalog.read_text(encoding="utf-8"))
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(build_tcl(data, catalog), encoding="utf-8")
    print(args.output)


if __name__ == "__main__":
    main()
