#!/usr/bin/env python3
"""Generate the 53 official TinyTapeout labels for flat Magic extraction."""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "v2/tools"))
from template_pins import submission_pins  # noqa: E402


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def um(value_nm: int) -> str:
    return f"{value_nm / 1000:.3f}um"


def generate(plan_path: Path) -> tuple[str, dict[str, object]]:
    plan = json.loads(plan_path.read_text(encoding="utf-8"))
    template = ROOT / plan["template"]["def"]
    if sha256(template) != plan["template"]["sha256"]:
        raise ValueError("TinyTapeout template DEF differs from the packaging plan")
    _width, _height, pins = submission_pins(template)
    lines = [
        "# Generated by v3/tools/generate_submission_magic_labels.py; do not edit.",
    ]
    for pin in pins:
        lx, by, rx, ty = pin.rect_nm
        x = (lx + rx) // 2
        y = (by + ty) // 2
        lines.append(f"box {um(x)} {um(y)} {um(x)} {um(y)}")
        lines.append(f"label {{{pin.name}}} FreeSans 0.10u -met4")
    text = "\n".join(lines) + "\n"
    return text, {
        "schema_version": 1,
        "status": "pass",
        "template_def": str(template.relative_to(ROOT)),
        "template_def_sha256": sha256(template),
        "label_count": len(pins),
        "signal_labels": sum(pin.use == "SIGNAL" for pin in pins),
        "power_ground_labels": sum(pin.use != "SIGNAL" for pin in pins),
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--plan", type=Path,
        default=ROOT / "v3/layout/submission_packaging_plan.json",
    )
    parser.add_argument(
        "--output", type=Path,
        default=ROOT / "build/v3/submission/official_magic_labels.tcl",
    )
    parser.add_argument(
        "--report", type=Path,
        default=ROOT / "build/v3/submission/official_magic_labels.json",
    )
    args = parser.parse_args()
    text, report = generate(args.plan)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(text, encoding="utf-8")
    report["output_sha256"] = hashlib.sha256(text.encode("utf-8")).hexdigest()
    args.report.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(json.dumps(report, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
