#!/usr/bin/env python3
"""Generate the matched differential output-load pair at the two output-pin axes."""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "v2/tools"))
from generate_critical_signal_routes import li_contact_stack, wire_h  # noqa: E402


CATALOG = ROOT / "v3/layout/shared_support_pcell_catalog.json"
DEFAULT_OUTPUT = ROOT / "build/v3/output_load_pair_block/build.tcl"
TOP = "v3_output_load_pair_block"
CENTRES = {"combined_n": [55.66, 123.0], "combined_p": [74.98, 123.0]}


def fmt(value: float) -> str:
    return f"{value:.6f}".rstrip("0").rstrip(".")


def component(name: str, center: list[float], cell: dict[str, Any]) -> dict[str, Any]:
    return {
        "name": name,
        "center": center,
        "anchor": [
            center[0] - cell["gencell_anchor_offset_um"][0],
            center[1] - cell["gencell_anchor_offset_um"][1],
        ],
        "R1": [center[0] + cell["ports"]["R1"][0]["point_um"][0], center[1] + cell["ports"]["R1"][0]["point_um"][1]],
        "R2": [center[0] + cell["ports"]["R2"][0]["point_um"][0], center[1] + cell["ports"]["R2"][0]["point_um"][1]],
    }


def build() -> str:
    catalog = json.loads(CATALOG.read_text(encoding="utf-8"))
    cell = catalog["cells"]["XOUTPUT_LOAD"]
    params = cell["parameters"]
    items = [component(name, center, cell) for name, center in CENTRES.items()]
    instances = []
    commands: list[str] = []
    for item in items:
        x, y = item["anchor"]
        instances.append(
            f"box {fmt(x)}um {fmt(y)}um {fmt(x)}um {fmt(y)}um\n"
            f"magic::gencell sky130::sky130_fd_pr__res_high_po_1p41 {item['name']} "
            f"w {fmt(params['width_um'])} l {fmt(params['length_um'])} m 1 guard 1 full_metal 1 doports 0"
        )
        commands.extend(li_contact_stack(*item["R1"]))
        commands.extend(li_contact_stack(*item["R2"]))
    commands.append(wire_h("metal2", items[0]["R1"][0], items[1]["R1"][0], items[0]["R1"][1], 0.80))
    labels = []
    for item in items:
        labels.append(f"""box {fmt(item['R2'][0]-0.20)}um {fmt(item['R2'][1]-0.20)}um {fmt(item['R2'][0]+0.20)}um {fmt(item['R2'][1]+0.20)}um
label {item['name']} center metal2
port make
port class bidirectional
port use signal
port connections n s e w""")
    power_x = (items[0]["R1"][0] + items[1]["R1"][0]) / 2.0
    power_y = items[0]["R1"][1]
    labels.append(f"""box {fmt(power_x-0.20)}um {fmt(power_y-0.20)}um {fmt(power_x+0.20)}um {fmt(power_y+0.20)}um
label VDPWR center metal2
port make
port class input
port use power
port connections n s e w""")
    return f"""# Generated by v3/tools/generate_output_load_pair_block.py; do not edit.
set PROJECT_ROOT [file normalize [pwd]]
set WORKDIR [file join $PROJECT_ROOT build v3 output_load_pair_block]
set SOURCE_TOP v3_output_load_pair_source
set TOP {TOP}
file mkdir $WORKDIR
cd $WORKDIR
foreach stale [glob -nocomplain [file join $WORKDIR ${{SOURCE_TOP}}*] [file join $WORKDIR ${{TOP}}*]] {{ file delete -force $stale }}
catch {{cellname delete $SOURCE_TOP}}
catch {{cellname delete $TOP}}
load $SOURCE_TOP -silent
{chr(10).join(instances)}
catch {{cellname delete {{(UNNAMED)}}}}
save $SOURCE_TOP.mag
writeall force
select top cell
expand
flatten $TOP
load $TOP
select top cell
proc paint_rect {{layer x1 y1 x2 y2}} {{
    box ${{x1}}um ${{y1}}um ${{x2}}um ${{y2}}um
    paint $layer
}}
{chr(10).join(commands)}
{chr(10).join(labels)}
save $TOP.mag
writeall force
select top cell
expand
drc euclidean on
drc style drc(full)
drc check
set drc_count [drc list count total]
puts "V3_OUTPUT_LOAD_PAIR_DRC_COUNT=$drc_count"
if {{$drc_count != 0}} {{
    feedback save [file join $WORKDIR drc_feedback.txt]
    error "output-load pair has DRC errors"
}}
extract unique notopports
extract do local
extract all
set extraction_feedback [feedback count]
puts "V3_OUTPUT_LOAD_PAIR_EXTRACTION_FEEDBACK_COUNT=$extraction_feedback"
if {{$extraction_feedback != 0}} {{
    feedback save [file join $WORKDIR extraction_feedback.txt]
    error "output-load pair extraction produced feedback"
}}
ext2spice lvs
ext2spice hierarchy off
ext2spice extresist off
ext2spice cthresh 1e99
ext2spice rthresh infinite
ext2spice -o [file join $WORKDIR ${{TOP}}_flat.spice] ${{TOP}}.ext
gds compress 0
gds write [file join $WORKDIR ${{TOP}}.gds]
puts "V3_OUTPUT_LOAD_PAIR_GDS_FEEDBACK_COUNT=[feedback count]"
quit -noprompt
"""


def main() -> None:
    DEFAULT_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    DEFAULT_OUTPUT.write_text(build(), encoding="utf-8")
    print(DEFAULT_OUTPUT)


if __name__ == "__main__":
    main()
