#!/usr/bin/env python3
"""Generate the four-wire, four-channel balanced phase-distribution H-tree."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from generate_critical_signal_routes import (
    fmt,
    via2_stack,
    via3_stack,
    wire_h,
    wire_v,
)


TOP = "v2_four_channel_phase_tree_routed"
STAGE = "global_phase_tree"
ROOT_Y = 174.0
LEAF_INTERFACE_Y = 151.0
TREE_WIDTH = 0.50


def generate(floorplan: dict[str, Any], output: Path) -> dict[str, Any]:
    channels = sorted(
        floorplan["channels"], key=lambda item: float(item["center_x"])
    )
    if len(channels) != 4:
        raise ValueError("the production phase tree requires exactly four channels")
    left_channels, right_channels = channels[:2], channels[2:]
    commands: list[str] = []
    metrics: dict[str, Any] = {}

    for phase in floorplan["clock_tree"]["phase_tracks"]:
        net = str(phase["net"])
        suffix = str(phase["selector_suffix"])
        offset = float(phase["x_offset"])
        root_branch_y = float(phase["root_branch_y"])
        leaf_branch_y = float(phase["leaf_branch_y"])
        leaf_x = {
            int(channel["index"]): float(channel["center_x"]) + offset
            for channel in channels
        }
        left_pair_x = sum(leaf_x[int(item["index"])] for item in left_channels) / 2.0
        right_pair_x = sum(leaf_x[int(item["index"])] for item in right_channels) / 2.0
        root_x = (left_pair_x + right_pair_x) / 2.0

        commands.append(f"# balanced global H-tree -> {net}")

        # M2 is the future digital phase-generator handoff.  The via2 is a
        # real endpoint transition, not a floating landing.
        commands.extend(via2_stack(root_x, ROOT_Y))
        commands.append(wire_v("metal3", root_x, root_branch_y, ROOT_Y, TREE_WIDTH))
        commands.extend(via3_stack(root_x, root_branch_y))
        commands.append(
            wire_h("metal4", left_pair_x, right_pair_x, root_branch_y, TREE_WIDTH)
        )

        per_leaf_paths: dict[str, float] = {}
        for pair_x, pair_channels in (
            (left_pair_x, left_channels),
            (right_pair_x, right_channels),
        ):
            commands.extend(via3_stack(pair_x, root_branch_y))
            commands.append(
                wire_v("metal3", pair_x, root_branch_y, leaf_branch_y, TREE_WIDTH)
            )
            commands.extend(via3_stack(pair_x, leaf_branch_y))
            pair_leaf_x = [leaf_x[int(item["index"])] for item in pair_channels]
            commands.append(
                wire_h(
                    "metal4", min(pair_leaf_x), max(pair_leaf_x),
                    leaf_branch_y, TREE_WIDTH,
                )
            )
            for channel in pair_channels:
                channel_index = int(channel["index"])
                x = leaf_x[channel_index]
                commands.extend(via3_stack(x, leaf_branch_y))
                commands.append(
                    wire_v(
                        "metal3", x, LEAF_INTERFACE_Y, leaf_branch_y, TREE_WIDTH
                    )
                )
                # This end overlaps the separately named local leaf from the
                # imported selector GDS.  The cumulative audit manifest lists
                # that intentional equivalence explicitly.
                per_leaf_paths[f"ch{channel_index}_{suffix}"] = (
                    ROOT_Y - root_branch_y
                    + abs(root_x - pair_x)
                    + root_branch_y - leaf_branch_y
                    + abs(pair_x - x)
                    + leaf_branch_y - LEAF_INTERFACE_Y
                )

        commands.extend((
            f"# net label: {net}",
            f"box {fmt(root_x)}um {fmt(ROOT_Y)}um {fmt(root_x)}um {fmt(ROOT_Y)}um",
            f"label {{{net}}} FreeSans 0.10u -met3",
        ))
        metrics[net] = {
            "root_x_um": root_x,
            "root_branch_y_um": root_branch_y,
            "leaf_branch_y_um": leaf_branch_y,
            "aggregate_m3_centerline_um": (
                ROOT_Y - root_branch_y
                + 2.0 * (root_branch_y - leaf_branch_y)
                + 4.0 * (leaf_branch_y - LEAF_INTERFACE_Y)
            ),
            "aggregate_m4_centerline_um": (
                right_pair_x - left_pair_x
                + sum(
                    max(leaf_x[int(item["index"])] for item in pair)
                    - min(leaf_x[int(item["index"])] for item in pair)
                    for pair in (left_channels, right_channels)
                )
            ),
            "via2_sites": 1,
            "via3_sites": 9,
            "root_to_leaf_centerline_um": per_leaf_paths,
        }

    body = "\n".join(commands)
    tcl = f"""# Generated by v2/tools/generate_global_phase_tree.py; do not edit.
set PROJECT_ROOT [pwd]
set SOURCE_GDS [file join $PROJECT_ROOT build v2 phase_selector_routes magic v2_four_channel_phase_routed.gds]
set OUT_DIR [file join $PROJECT_ROOT build v2 {STAGE} magic]
file mkdir $OUT_DIR
if {{![file exists $SOURCE_GDS]}} {{
    error "required phase-selector GDS does not exist: $SOURCE_GDS"
}}
gds read $SOURCE_GDS
if {{[lsearch -exact [cellname list all] v2_four_channel_phase_routed] < 0}} {{
    error "phase-selector top cell was not imported"
}}
load v2_four_channel_phase_routed
cellname rename {TOP}
select top cell
expand

proc paint_rect {{layer x1 y1 x2 y2}} {{
    box ${{x1}}um ${{y1}}um ${{x2}}um ${{y2}}um
    paint $layer
}}

{body}

select top cell
expand
drc euclidean on
drc style drc(full)
drc check
set drc_count [drc list count total]
puts "GLOBAL_PHASE_TREE_DRC_COUNT=$drc_count"
if {{$drc_count != 0}} {{
    feedback save [file join $OUT_DIR global_phase_tree_drc.txt]
    error "refusing global-phase-tree artifact with $drc_count DRC errors"
}}
cd $OUT_DIR
save {TOP}.mag
feedback clear
gds compress 0
gds write {TOP}.gds
set gds_feedback [feedback count]
puts "GLOBAL_PHASE_TREE_GDS_FEEDBACK_COUNT=$gds_feedback"
if {{$gds_feedback != 0}} {{
    feedback save global_phase_tree_gds_feedback.txt
    error "refusing global-phase-tree artifact with $gds_feedback writer problems"
}}
quit -noprompt
"""
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(tcl, encoding="utf-8")
    return metrics


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--floorplan", type=Path, default=Path("v2/layout/floorplan.json"))
    parser.add_argument(
        "--output", type=Path,
        default=Path("build/v2/global_phase_tree/route.tcl"),
    )
    args = parser.parse_args()
    metrics = generate(
        json.loads(args.floorplan.read_text(encoding="utf-8")), args.output
    )
    print(json.dumps(metrics, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
