#!/usr/bin/env python3
"""Generate deterministic Magic placement for the measured analog channel core.

The generated PCells have a local origin at their measured bounding-box centre.
Magic calls its x-reflection transform ``h``; this is the matrix (-1,0,0,1)
and therefore implements the template's MY orientation.  Using ``v`` here
would incorrectly implement MX.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


MAGIC_TRANSFORM = {"R0": "", "MY": " h 0 0"}


def fmt(value: float) -> str:
    return f"{value:.9g}"


def generate(
    dimensions: dict[str, Any], template: dict[str, Any], output: Path
) -> int:
    pcells = dimensions["pcells"]
    components = [
        component
        for component in template["components"]
        if not component["pcell"].startswith("sc_hd_")
    ]
    commands: list[str] = []
    for component in components:
        cell = pcells[component["pcell"]]
        x0, y0, x1, y1 = map(float, cell["bbox_um"])
        if abs(x0 + x1) > 1e-9 or abs(y0 + y1) > 1e-9:
            raise ValueError(
                f"{component['name']}: analog PCell bbox is not centred on its origin"
            )
        orientation = component["orientation"]
        if orientation not in MAGIC_TRANSFORM:
            raise ValueError(f"{component['name']}: unsupported orientation {orientation}")
        x = fmt(float(component["x"]))
        y = fmt(float(component["y"]))
        commands.extend(
            (
                f"# {component['name']} {component['role']} {orientation}",
                f"box {x}um {y}um {x}um {y}um",
                f"getcell {cell['generated_cell']} child 0 0 parent ll"
                f"{MAGIC_TRANSFORM[orientation]}",
                f"identify {component['name']}",
                "",
            )
        )

    script = f"""# Generated by v2/tools/generate_analog_placement_tcl.py; do not edit.
set PROJECT_ROOT [pwd]
set PCELL_DIR [file join $PROJECT_ROOT build v2 pcell_bbox_switched_tail_r5]
set OUT_DIR [file join $PROJECT_ROOT build v2 analog_placement]
file mkdir $OUT_DIR
addpath $PCELL_DIR
cd $OUT_DIR

# A placement run must never inherit instances from an older generated MAG.
# Delete only this named build artifact, then create a fresh empty cell.
file delete -force [file join $OUT_DIR v2_analog_channel_placement.mag]
catch {{cellname delete v2_analog_channel_placement}}
load v2_analog_channel_placement -silent
{chr(10).join(commands)}
save v2_analog_channel_placement.mag
select top cell
expand
drc euclidean on
drc style drc(full)
drc check
set drc_count [drc list count total]
puts "ANALOG_PLACEMENT_DRC_COUNT=$drc_count"
if {{$drc_count != 0}} {{
    feedback save analog_placement_drc.txt
    error "refusing analog placement artifact with $drc_count DRC errors"
}}
feedback clear
gds compress 0
gds write v2_analog_channel_placement.gds
set gds_feedback [feedback count]
puts "ANALOG_PLACEMENT_GDS_FEEDBACK_COUNT=$gds_feedback"
if {{$gds_feedback != 0}} {{
    feedback save analog_placement_gds_feedback.txt
    error "refusing analog placement artifact with $gds_feedback GDS writer problems"
}}
quit -noprompt
"""
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(script, encoding="utf-8")
    return len(components)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("dimensions", type=Path)
    parser.add_argument("template", type=Path)
    parser.add_argument("output", type=Path)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    count = generate(
        json.loads(args.dimensions.read_text(encoding="utf-8")),
        json.loads(args.template.read_text(encoding="utf-8")),
        args.output,
    )
    print(f"{args.output} ({count} analog components)")


if __name__ == "__main__":
    main()
