#!/usr/bin/env python3
"""Render the audited V2 standard-cell placement as a Magic Tcl script."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


TOP = "v2_four_channel_control_placed"
STAGE = "control_placement"
TRANSFORM = {"R0": "", "MX": " v 0 0", "MY": " h 0 0", "R180": " 180 0 0"}
SOURCE_LIBRARY_CELLS = {
    "sky130_fd_sc_hd__and2_1",
    "sky130_fd_sc_hd__buf_4",
    "sky130_fd_sc_hd__inv_1",
    "sky130_fd_sc_hd__mux2_1",
    "sky130_fd_sc_hd__tapvpwrvgnd_1",
}


def fmt(value: float) -> str:
    return f"{value:.9g}"


def generate(
    placement: dict[str, Any], integration: dict[str, Any], output: Path
) -> int:
    source = integration["base_checkpoint"]
    instances = (
        placement["placements"]
        + placement["well_taps"]
        + placement.get("fillers", [])
    )
    cells = sorted({item["cell"] for item in instances})
    missing_cells = [cell for cell in cells if cell not in SOURCE_LIBRARY_CELLS]
    commands: list[str] = []
    for index, item in enumerate(instances):
        orientation = item["orientation"]
        if orientation not in TRANSFORM:
            raise ValueError(f"{item['instance']}: unsupported orientation {orientation}")
        x, y = map(float, item["origin_um"])
        commands.extend((
            f"# {item['role']}: {item['rationale']}",
            f"box {fmt(x)}um {fmt(y)}um {fmt(x)}um {fmt(y)}um",
            f"getcell {item['cell']} child 0 0 parent ll{TRANSFORM[orientation]}",
            # Magic/GDS instance identifiers reject '/', '$', ':', and '['.
            # The lossless logical name remains in control_placement.json.
            f"identify U_CTRL_{index:03d}",
            "",
        ))
    gds_imports = "\n".join(
        f"gds read [file join $CELL_DIR {cell}.gds]" for cell in missing_cells
    )
    body = "\n".join(commands)
    text = f"""# Generated by v2/tools/generate_control_placement_tcl.py; do not edit.
set PROJECT_ROOT [pwd]
set SOURCE_GDS [file join $PROJECT_ROOT {source['gds']}]
set CELL_DIR [file join $PROJECT_ROOT third_party sky130_fd_sc_hd_cells]
set OUT_DIR [file join $PROJECT_ROOT build v2 {STAGE} magic]
file mkdir $OUT_DIR
if {{![file exists $SOURCE_GDS]}} {{
    error "required support-routed GDS does not exist: $SOURCE_GDS"
}}
gds readonly no
gds read $SOURCE_GDS
gds readonly yes
{gds_imports}
gds readonly no
if {{[lsearch -exact [cellname list all] {source['top']}] < 0}} {{
    error "support-routed top cell was not imported"
}}
load {source['top']}
cellname rename {TOP}
select top cell
expand

{body}

select top cell
expand
drc euclidean on
drc style drc(full)
drc check
set drc_count [drc list count total]
puts "CONTROL_PLACEMENT_DRC_COUNT=$drc_count"
if {{$drc_count != 0}} {{
    feedback save [file join $OUT_DIR control_placement_drc.txt]
    error "refusing control placement with $drc_count DRC errors"
}}
cd $OUT_DIR
save {TOP}.mag
puts "CONTROL_PLACEMENT_MAG_SAVED=1"
puts "CONTROL_PLACEMENT_GDS_POLICY=direct_hierarchy_assembly"
quit -noprompt
"""
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(text, encoding="utf-8")
    return len(instances)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("placement", type=Path)
    parser.add_argument("integration", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    count = generate(
        json.loads(args.placement.read_text(encoding="utf-8")),
        json.loads(args.integration.read_text(encoding="utf-8")),
        args.output,
    )
    print(f"{args.output}: {count} placed standard-cell/tap/filler instances")


if __name__ == "__main__":
    main()
