#!/usr/bin/env python3
"""Generate a mixed DEF/Magic four-channel placement-only validation cell."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


DEF_ORIENTATION = {"R0": "N", "MY": "FN"}
MAGIC_TRANSFORM = {"R0": "", "MY": " h 0 0"}
STANDARD_CELLS = ("mux2_1", "and2_1", "buf_4", "inv_1", "tapvpwrvgnd_1")
TOP = "v2_four_channel_placement"


def dbu(value_um: float) -> int:
    return round(value_um * 1000.0)


def fmt(value: float) -> str:
    return f"{value:.9g}"


def generate(
    floorplan: dict[str, Any],
    dimensions: dict[str, Any],
    template: dict[str, Any],
    def_output: Path,
    tcl_output: Path,
) -> tuple[int, int]:
    pcells = dimensions["pcells"]
    standard_components = [
        component
        for component in template["components"]
        if component["pcell"].startswith("sc_hd_")
    ]
    analog_components = [
        component
        for component in template["components"]
        if not component["pcell"].startswith("sc_hd_")
    ]

    def_components: list[str] = []
    analog_commands: list[str] = []
    for channel in floorplan["channels"]:
        channel_index = int(channel["index"])
        center_x = float(channel["center_x"])
        for component in standard_components:
            cell = pcells[component["pcell"]]
            x = center_x + float(component["x"]) - float(cell["width_um"]) / 2.0
            y = float(component["y"]) - float(cell["height_um"]) / 2.0
            name = f"CH{channel_index}_{component['name']}"
            def_components.append(
                f"- {name} {cell['generated_cell']} + FIXED "
                f"( {dbu(x)} {dbu(y)} ) {DEF_ORIENTATION[component['orientation']]} ;"
            )
        for component in analog_components:
            cell = pcells[component["pcell"]]
            x = center_x + float(component["x"])
            y = float(component["y"])
            name = f"CH{channel_index}_{component['name']}"
            transform = MAGIC_TRANSFORM[component["orientation"]]
            analog_commands.extend(
                (
                    f"# {name} {component['role']} {component['orientation']}",
                    f"box {fmt(x)}um {fmt(y)}um {fmt(x)}um {fmt(y)}um",
                    f"getcell {cell['generated_cell']} child 0 0 parent ll{transform}",
                    f"identify {name}",
                    "",
                )
            )

    # The differential loads are shared structures, not duplicated channel
    # components.  Their corrected centers are symmetric about the actual
    # collector axis (124.20 um), which is 0.92 um right of the pin-center
    # arithmetic mean because every local analog slice uses that internal
    # symmetry axis.
    load_cell = pcells["output_load_resistor_guarded"]
    for polarity in ("p", "n"):
        x, y = map(float, floorplan["output_pair"][f"load_{polarity}_center"])
        name = f"LOAD_{polarity.upper()}"
        analog_commands.extend((
            f"# {name} shared_differential_load R0",
            f"box {fmt(x)}um {fmt(y)}um {fmt(x)}um {fmt(y)}um",
            f"getcell {load_cell['generated_cell']} child 0 0 parent ll",
            f"identify {name}",
            "",
        ))

    die = floorplan["template"]["die"]
    def_lines = [
        "VERSION 5.8 ;",
        'DIVIDERCHAR "/" ;',
        'BUSBITCHARS "[]" ;',
        f"DESIGN {TOP} ;",
        "UNITS DISTANCE MICRONS 1000 ;",
        f"DIEAREA ( 0 0 ) ( {dbu(float(die['width']))} {dbu(float(die['height']))} ) ;",
        f"COMPONENTS {len(def_components)} ;",
        *def_components,
        "END COMPONENTS",
        "PINS 0 ;",
        "END PINS",
        "NETS 0 ;",
        "END NETS",
        "END DESIGN",
    ]
    def_output.parent.mkdir(parents=True, exist_ok=True)
    def_output.write_text("\n".join(def_lines) + "\n", encoding="utf-8")

    tcl = f"""# Generated by v2/tools/generate_four_channel_placement.py; do not edit.
set PROJECT_ROOT [pwd]
set CELL_DIR [file join $PROJECT_ROOT third_party sky130_fd_sc_hd_cells]
set PCELL_DIR [file join $PROJECT_ROOT build v2 pcell_bbox_switched_tail_r5]
set DEF_FILE [file join $PROJECT_ROOT {def_output.as_posix()}]
set OUT_DIR [file join $PROJECT_ROOT build v2 four_channel_placement magic]
file mkdir $OUT_DIR
addpath $PCELL_DIR

foreach cell {{{' '.join(STANDARD_CELLS)}}} {{
    lef read [file join $CELL_DIR sky130_fd_sc_hd__${{cell}}.lef]
}}
foreach cell {{{' '.join(STANDARD_CELLS)}}} {{
    gds read [file join $CELL_DIR sky130_fd_sc_hd__${{cell}}.gds]
}}

def read $DEF_FILE
{chr(10).join(analog_commands)}
select top cell
expand
drc euclidean on
drc style drc(full)
drc check
set drc_count [drc list count total]
puts "FOUR_CHANNEL_PLACEMENT_DRC_COUNT=$drc_count"
if {{$drc_count != 0}} {{
    feedback save [file join $OUT_DIR four_channel_placement_drc.txt]
    error "refusing four-channel placement artifact with $drc_count DRC errors"
}}

cd $OUT_DIR
save {TOP}.mag
feedback clear
gds compress 0
gds write {TOP}.gds
set gds_feedback [feedback count]
puts "FOUR_CHANNEL_PLACEMENT_GDS_FEEDBACK_COUNT=$gds_feedback"
if {{$gds_feedback != 0}} {{
    feedback save four_channel_placement_gds_feedback.txt
    error "refusing four-channel placement artifact with $gds_feedback GDS writer problems"
}}
quit -noprompt
"""
    tcl_output.parent.mkdir(parents=True, exist_ok=True)
    tcl_output.write_text(tcl, encoding="utf-8")
    return len(def_components), len(analog_commands) // 5


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("floorplan", type=Path)
    parser.add_argument("dimensions", type=Path)
    parser.add_argument("template", type=Path)
    parser.add_argument("def_output", type=Path)
    parser.add_argument("tcl_output", type=Path)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    standard, analog = generate(
        json.loads(args.floorplan.read_text(encoding="utf-8")),
        json.loads(args.dimensions.read_text(encoding="utf-8")),
        json.loads(args.template.read_text(encoding="utf-8")),
        args.def_output,
        args.tcl_output,
    )
    print(f"{args.def_output}: {standard} standard cells")
    print(f"{args.tcl_output}: {analog} analog components")


if __name__ == "__main__":
    main()
