#!/usr/bin/env python3
"""Generate the four-tile VCM-varactor ECO without touching proven routes."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from check_route_feasibility import component_ports
from generate_critical_signal_routes import (
    contact_stack,
    fmt,
    li_contact_stack,
    li_to_m1_stack,
    via2_stack,
    via3_stack,
    wire_h,
    wire_v,
)


TOP = "v2_vcm_varactor_eco_overlay"
PCELL_DIR = "build/v2/pcell_bbox_remote"
M2_WIDTH = 0.32
M3_WIDTH = 0.40
M4_WIDTH = 0.40
VCM_SPINE_X = 53.88
VCM_BUS_Y = 83.765
GROUND_SPINE_X = 28.18
GROUND_JOIN_Y = 20.0


def placed_component(record: dict[str, Any]) -> dict[str, Any]:
    return {
        "name": record["name"],
        "pcell": record["pcell"],
        "x": record["center"][0],
        "y": record["center"][1],
        "orientation": record["orientation"],
    }


def generate(
    plan: dict[str, Any], dimensions: dict[str, Any], catalog: dict[str, Any],
    output: Path,
) -> dict[str, Any]:
    records = sorted(
        (
            item for item in plan["analog_support_components"]
            if item.get("implementation_stage") == "vcm_varactor_eco"
        ),
        key=lambda item: item["name"],
    )
    if [item["name"] for item in records] != [
        "CVCM_VAR0", "CVCM_VAR1", "CVCM_VAR2", "CVCM_VAR3"
    ]:
        raise ValueError("the ECO requires exactly CVCM_VAR0..CVCM_VAR3")
    if any(item["orientation"] != "R0" for item in records):
        raise ValueError("the four ECO varactors must retain R0 orientation")

    components = {item["name"]: placed_component(item) for item in records}

    def port(name: str, terminal: str) -> list[float]:
        return component_ports(
            components[name], terminal, dimensions, catalog
        )[0]

    commands: list[str] = []
    gate_points: list[list[float]] = []
    gate_access_points: list[list[float]] = []
    body_points: list[list[float]] = []
    for item in records:
        pcell = dimensions["pcells"][item["pcell"]]
        x, y = map(float, item["center"])
        commands.extend((
            f"# {item['name']} {item['pcell']} R0",
            f"box {fmt(x)}um {fmt(y)}um {fmt(x)}um {fmt(y)}um",
            f"getcell {pcell['generated_cell']} child 0 0 parent ll",
            f"identify {item['name']}",
        ))
        gate = port(item["name"], "G")
        drain = port(item["name"], "D")
        body = port(item["name"], "B")
        gate_points.append(gate)
        body_points.append(body)

        commands.append(f"# {item['name']}.G -> existing vcm spine")
        # Keep the via1 landing clear of unrelated M1 inside the foundry
        # varactor.  The LI terminal itself gets the minimum legal M1
        # enclosure, then a short monotonic M1 escape reaches the M2 landing.
        gate_access = [gate[0], gate[1] + 0.32]
        gate_access_points.append(gate_access)
        commands.extend(li_to_m1_stack(gate[0], gate[1]))
        # The PCell's gate M1 has symmetric side shoulders.  A 0.60 um neck
        # joins both shoulders and avoids narrow same-net notches before the
        # via1 pad, while starting high enough to clear unrelated lower M1.
        commands.append(wire_v(
            "metal1", gate[0], gate[1], gate_access[1], 0.60
        ))
        commands.extend(contact_stack(gate_access[0], gate_access[1]))
        commands.append(wire_h(
            "metal2", gate_access[0], VCM_SPINE_X, gate_access[1], M2_WIDTH
        ))
        commands.extend(via2_stack(VCM_SPINE_X, gate_access[1]))
        commands.extend(via3_stack(VCM_SPINE_X, gate_access[1]))

        # The foundry PCell straps D and S internally.  D is the nearer ground
        # access; B is the independent guard/body terminal.
        commands.append(f"# {item['name']}.D(S) + {item['name']}.B -> existing VGND spine")
        for point in (drain, body):
            commands.extend(li_contact_stack(point[0], point[1]))
            commands.append(wire_h(
                "metal2", GROUND_SPINE_X, point[0], point[1], M2_WIDTH
            ))
            commands.extend(via2_stack(GROUND_SPINE_X, point[1]))

    commands.append("# one direct VCM extension; the base GDS owns the bus above 83.765 um")
    commands.append(wire_v(
        "metal4", VCM_SPINE_X, min(point[1] for point in gate_access_points),
        VCM_BUS_Y, M4_WIDTH,
    ))
    commands.append("# one direct ground extension; the base GDS owns the via3 at y=20 um")
    commands.append(wire_v(
        "metal3", GROUND_SPINE_X, min(point[1] for point in body_points),
        GROUND_JOIN_Y, M3_WIDTH,
    ))

    body = "\n".join(commands)
    tcl = f"""# Generated by v2/tools/generate_vcm_varactor_eco.py; do not edit.
set PROJECT_ROOT [pwd]
set PCELL_DIR [file join $PROJECT_ROOT {PCELL_DIR}]
set OUT_DIR [file join $PROJECT_ROOT build v2 varactor_eco overlay]
file mkdir $OUT_DIR
addpath $PCELL_DIR
catch {{cellname delete {TOP}}}
load {TOP} -silent

proc paint_rect {{layer x1 y1 x2 y2}} {{
    box ${{x1}}um ${{y1}}um ${{x2}}um ${{y2}}um
    paint $layer
}}

{body}

select top cell
expand
drc euclidean on
drc style drc(full)
drc check
set drc_count [drc list count total]
puts "VCM_VARACTOR_ECO_OVERLAY_DRC_COUNT=$drc_count"
if {{$drc_count != 0}} {{
    feedback save [file join $OUT_DIR overlay_drc.txt]
    error "refusing a varactor ECO overlay with $drc_count DRC errors"
}}
cd $OUT_DIR
save {TOP}.mag
feedback clear
gds compress 0
gds write {TOP}.gds
set feedback_count [feedback count]
puts "VCM_VARACTOR_ECO_OVERLAY_GDS_FEEDBACK_COUNT=$feedback_count"
if {{$feedback_count != 0}} {{
    error "varactor ECO overlay produced GDS writer feedback"
}}
quit -noprompt
"""
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(tcl, encoding="utf-8")
    return {
        "varactor_count": len(records),
        "varactor_pcell": records[0]["pcell"],
        "centres_um": [item["center"] for item in records],
        "gate_points_um": gate_points,
        "gate_access_points_um": gate_access_points,
        "vcm_spine_x_um": VCM_SPINE_X,
        "ground_spine_x_um": GROUND_SPINE_X,
        "ground_extension_bottom_y_um": min(point[1] for point in body_points),
        "direction_reversals": 0,
        "orphan_vias": 0,
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--plan", type=Path, default=Path("v2/layout/integration_plan.json"))
    parser.add_argument("--dimensions", type=Path, default=Path("v2/layout/pcell_dimensions.json"))
    parser.add_argument("--catalog", type=Path, default=Path("v2/layout/port_catalog.json"))
    parser.add_argument(
        "--output", type=Path,
        default=Path("build/v2/varactor_eco/generate_overlay.tcl"),
    )
    parser.add_argument(
        "--report", type=Path,
        default=Path("build/v2/varactor_eco/generator_metrics.json"),
    )
    args = parser.parse_args()
    metrics = generate(
        json.loads(args.plan.read_text(encoding="utf-8")),
        json.loads(args.dimensions.read_text(encoding="utf-8")),
        json.loads(args.catalog.read_text(encoding="utf-8")),
        args.output,
    )
    args.report.parent.mkdir(parents=True, exist_ok=True)
    args.report.write_text(json.dumps(metrics, indent=2, sort_keys=True) + "\n")
    print(json.dumps(metrics, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
