#!/usr/bin/env python3
"""Generate Magic ``res:force@`` attributes for every routed signal net.

Magic normally omits undriven/gate-only nets from distributed-resistance
extraction.  That behavior is useful for digital timing, but it is unsafe for
analog VCM/input/reference wiring.  This generator reuses the exact label
locations already emitted by each route stage, so the RC flow cannot drift
from the routed geometry.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path


BOX_RE = re.compile(
    r"^box\s+([-+0-9.]+)um\s+([-+0-9.]+)um\s+"
    r"([-+0-9.]+)um\s+([-+0-9.]+)um$"
)
LABEL_RE = re.compile(r"^label\s+\{([^}]+)\}.*\s+-(met[1-5])$")
EXTERNAL_UNDRIVEN_RE = re.compile(
    r"^(?:ch[0-3]_input|ch[0-3]_phase_sel[01]|ch[0-3]_phase_enable|"
    r"phase_(?:0|90|180|270)|vcm)$"
)
DRIVE_ONLY_RE = re.compile(r"^ch[0-3]_lo[pn]$")
# The differential output nets are electrically driven by transistor drains,
# but the bare output pads are not device terminals.  Without an explicit
# endpoint Magic can legally prune the long pad branch from its resistor mesh.
# ``res:drive@`` is therefore used as a computational RC anchor at each pad;
# it does not add a source or geometry to the manufactured GDS.  Resistance is
# bidirectional, so rooting the mesh at the measurement pad preserves the
# complete pad-to-device network needed by post-layout simulation.
FORCE_ONLY_RE = re.compile(r"^sum_[pn]$")
DEFAULT_ROUTES = (
    Path("build/v2/local_channel_routes/route.tcl"),
    Path("build/v2/phase_selector_routes/route.tcl"),
    Path("build/v2/global_phase_tree/route.tcl"),
    Path("build/v2/output_summing_routes/route.tcl"),
    Path("build/v2/support_routes/route.tcl"),
)


def collect_labels(paths: list[Path]) -> list[tuple[str, str, str, str, str]]:
    labels: list[tuple[str, str, str, str, str]] = []
    seen: set[tuple[str, str, str, str, str]] = set()
    for path in paths:
        previous = ""
        for raw in path.read_text(encoding="utf-8").splitlines():
            line = raw.strip()
            match = LABEL_RE.match(line)
            if match:
                box = BOX_RE.match(previous)
                if box is None:
                    raise ValueError(f"{path}: label is not preceded by a point box")
                net, layer = match.groups()
                # Force only nets that are intentionally external/undriven at
                # this checkpoint.  Device-driven nets are left to extresist;
                # forcing those can conflict with its discovered drive point.
                if (
                    EXTERNAL_UNDRIVEN_RE.match(net)
                    or DRIVE_ONLY_RE.match(net)
                    or FORCE_ONLY_RE.match(net)
                ):
                    item = (net, *box.groups(), layer)
                    if item not in seen:
                        labels.append(item)
                        seen.add(item)
            previous = line
    if not labels:
        raise ValueError("no routed labels found")
    return labels


def generate(paths: list[Path], output: Path) -> int:
    labels = collect_labels(paths)
    lines = [
        "# Generated by v2/tools/generate_rc_force_attributes.py; do not edit.",
        "# Applied only to the temporary flattened RC-extraction cell.",
    ]
    for net, x1, y1, x2, y2, layer in labels:
        lines.extend((
            f"# explicit RC drive point for {net}",
            f"box {x1}um {y1}um {x2}um {y2}um",
        ))
        if EXTERNAL_UNDRIVEN_RE.match(net) or FORCE_ONLY_RE.match(net):
            lines.append(f"label {{res:force@}} FreeSans 0.10u -{layer}")
        if (
            EXTERNAL_UNDRIVEN_RE.match(net)
            or DRIVE_ONLY_RE.match(net)
            or FORCE_ONLY_RE.match(net)
        ):
            lines.append(f"label {{res:drive@}} FreeSans 0.10u -{layer}")
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return len(labels)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("routes", nargs="*", type=Path, default=list(DEFAULT_ROUTES))
    parser.add_argument(
        "--output", type=Path,
        default=Path("build/v2/support_routes/rc_force_attributes.tcl"),
    )
    args = parser.parse_args()
    count = generate(args.routes, args.output)
    print(f"{args.output}: annotated {count} routed signal labels")


if __name__ == "__main__":
    main()
