#!/usr/bin/env python3
"""Place the measured shared VCM and bias-reference cells on the V2 GDS."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


TOP = "v2_four_channel_support_placed"
STAGE = "support_placement"
MAGIC_TRANSFORM = {"R0": "", "MY": " h 0 0"}


def fmt(value: float) -> str:
    return f"{value:.9g}"


def generate(plan: dict[str, Any], dimensions: dict[str, Any], output: Path) -> int:
    commands: list[str] = []
    for component in plan["analog_support_components"]:
        orientation = component["orientation"]
        if orientation not in MAGIC_TRANSFORM:
            raise ValueError(
                f"{component['name']}: unsupported orientation {orientation}"
            )
        pcell = dimensions["pcells"][component["pcell"]]
        x0, y0, x1, y1 = map(float, pcell["bbox_um"])
        if abs(x0 + x1) > 1e-9 or abs(y0 + y1) > 1e-9:
            raise ValueError(f"{component['name']}: PCell is not origin-centred")
        x, y = map(float, component["center"])
        commands.extend(
            (
                f"# {component['name']} {component['pcell']} {orientation}",
                f"box {fmt(x)}um {fmt(y)}um {fmt(x)}um {fmt(y)}um",
                f"getcell {pcell['generated_cell']} child 0 0 parent ll"
                f"{MAGIC_TRANSFORM[orientation]}",
                f"identify {component['name']}",
                "",
            )
        )

    body = "\n".join(commands)
    source = plan["base_checkpoint"]["gds"]
    source_top = plan["base_checkpoint"]["top"]
    tcl = f"""# Generated by v2/tools/generate_support_placement.py; do not edit.
set PROJECT_ROOT [pwd]
set SOURCE_GDS [file join $PROJECT_ROOT {source}]
set PCELL_DIR [file join $PROJECT_ROOT build v2 pcell_bbox_switched_tail_r5]
set OUT_DIR [file join $PROJECT_ROOT build v2 {STAGE} magic]
file mkdir $OUT_DIR
if {{![file exists $SOURCE_GDS]}} {{
    error "required routed GDS does not exist: $SOURCE_GDS"
}}
addpath $PCELL_DIR
gds read $SOURCE_GDS
if {{[lsearch -exact [cellname list all] {source_top}] < 0}} {{
    error "base checkpoint top cell was not imported"
}}
load {source_top}
cellname rename {TOP}
select top cell
expand

{body}

select top cell
expand
drc euclidean on
drc style drc(full)
drc check
set drc_count [drc list count total]
puts "SUPPORT_PLACEMENT_DRC_COUNT=$drc_count"
if {{$drc_count != 0}} {{
    feedback save [file join $OUT_DIR support_placement_drc.txt]
    error "refusing support placement with $drc_count DRC errors"
}}
cd $OUT_DIR
save {TOP}.mag
feedback clear
gds compress 0
gds write {TOP}.gds
set gds_feedback [feedback count]
puts "SUPPORT_PLACEMENT_GDS_FEEDBACK_COUNT=$gds_feedback"
if {{$gds_feedback != 0}} {{
    feedback save support_placement_gds_feedback.txt
    error "refusing support placement with $gds_feedback GDS writer problems"
}}
quit -noprompt
"""
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(tcl, encoding="utf-8")
    return len(commands) // 5


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--plan", type=Path, default=Path("v2/layout/integration_plan.json")
    )
    parser.add_argument(
        "--dimensions", type=Path, default=Path("v2/layout/pcell_dimensions.json")
    )
    parser.add_argument(
        "--output", type=Path,
        default=Path("build/v2/support_placement/place.tcl"),
    )
    args = parser.parse_args()
    count = generate(
        json.loads(args.plan.read_text(encoding="utf-8")),
        json.loads(args.dimensions.read_text(encoding="utf-8")),
        args.output,
    )
    print(f"{args.output}: {count} measured support components")


if __name__ == "__main__":
    main()
