#!/usr/bin/env python3
"""Run a hash-bound subset of the post-layout trim matrix.

This is a throughput helper, not an alternate electrical test.  It calls the
same single-case runner and reusable-report predicate as the authoritative
64-case calibration flow.  A shard report never claims full calibration; the
complete summary must still be generated by run_control_postlayout_trim_calibration.py.
"""

from __future__ import annotations

import argparse
import concurrent.futures
import json
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

from v2.tools.run_control_postlayout_trim_calibration import (  # noqa: E402
    BUILD,
    GDS,
    NETLIST_BY_VIEW,
    case_report_path,
    reusable_report,
    run_case,
    sha256,
)


def parse_selection(text: str, *, minimum: int, maximum: int) -> list[int]:
    """Parse comma-separated integers and inclusive ranges."""
    selected: set[int] = set()
    for raw_part in text.split(","):
        part = raw_part.strip()
        if not part:
            raise ValueError("empty selection component")
        if "-" in part:
            raw_start, raw_stop = part.split("-", 1)
            start, stop = int(raw_start), int(raw_stop)
            if stop < start:
                raise ValueError(f"descending range is not allowed: {part}")
            selected.update(range(start, stop + 1))
        else:
            selected.add(int(part))
    if not selected:
        raise ValueError("selection is empty")
    if min(selected) < minimum or max(selected) > maximum:
        raise ValueError(
            f"selection must stay between {minimum} and {maximum}: {text}"
        )
    return sorted(selected)


def shard_label(channels: list[int], codes: list[int]) -> str:
    return (
        "channels_" + "-".join(str(value) for value in channels)
        + "_codes_" + "-".join(str(value) for value in codes)
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--view", choices=("base", "rc"), default="rc")
    parser.add_argument("--channels", default="0-3")
    parser.add_argument("--codes", default="0-15")
    parser.add_argument("--ngspice", default="ngspice")
    parser.add_argument("--timeout", type=int, default=1800)
    parser.add_argument("--jobs", type=int, default=2)
    parser.add_argument("--transient-step-ns", type=float, default=5.0)
    parser.add_argument("--analysis-start-us", type=float, default=2.0)
    parser.add_argument("--analysis-stop-us", type=float, default=3.0)
    parser.add_argument(
        "--resume",
        action="store_true",
        help="reuse only exact passing reports for the current artifacts",
    )
    args = parser.parse_args()
    if not 1 <= args.jobs <= 4:
        raise SystemExit("--jobs must be between one and four")
    try:
        channels = parse_selection(args.channels, minimum=0, maximum=3)
        codes = parse_selection(args.codes, minimum=0, maximum=15)
    except ValueError as error:
        raise SystemExit(str(error)) from error

    gds_sha = sha256(GDS)
    netlist_sha = sha256(NETLIST_BY_VIEW[args.view])
    cases = [(channel, code) for channel in channels for code in codes]
    reused: list[tuple[int, int]] = []
    pending: list[tuple[int, int]] = []
    for channel, code in cases:
        path = case_report_path(
            channel,
            code,
            args.view,
            args.transient_step_ns,
            args.analysis_start_us,
            args.analysis_stop_us,
        )
        if args.resume and reusable_report(
            path,
            channel,
            code,
            args.view,
            args.transient_step_ns,
            args.analysis_start_us,
            args.analysis_stop_us,
            gds_sha,
            netlist_sha,
        ):
            reused.append((channel, code))
        else:
            pending.append((channel, code))

    execution_errors: list[str] = []
    with concurrent.futures.ThreadPoolExecutor(max_workers=args.jobs) as executor:
        futures = [
            executor.submit(
                run_case,
                channel,
                code,
                args.view,
                args.ngspice,
                args.timeout,
                args.transient_step_ns,
                args.analysis_start_us,
                args.analysis_stop_us,
            )
            for channel, code in pending
        ]
        for future in concurrent.futures.as_completed(futures):
            channel, code, returncode, output = future.result()
            if returncode:
                execution_errors.append(
                    f"channel {channel} code {code} returned {returncode}: {output[-500:]!r}"
                )
            print(
                f"channel={channel} code={code} returncode={returncode}",
                flush=True,
            )

    records = []
    for channel, code in cases:
        path = case_report_path(
            channel,
            code,
            args.view,
            args.transient_step_ns,
            args.analysis_start_us,
            args.analysis_stop_us,
        )
        passed = reusable_report(
            path,
            channel,
            code,
            args.view,
            args.transient_step_ns,
            args.analysis_start_us,
            args.analysis_stop_us,
            gds_sha,
            netlist_sha,
        )
        record = {
            "channel": channel,
            "code": code,
            "status": "pass" if passed else "fail",
            "report": str(path.relative_to(ROOT)),
        }
        if path.is_file():
            report = json.loads(path.read_text(encoding="utf-8"))
            record.update(
                {
                    "report_sha256": sha256(path),
                    "elapsed_s": report.get("elapsed_s"),
                    "output_tone_rms_v": report.get("analysis", {}).get(
                        "output_tone_rms_v"
                    ),
                    "output_common_mode_v": report.get("analysis", {}).get(
                        "output_common_mode_v"
                    ),
                    "supply_current_a": report.get("analysis", {}).get(
                        "supply_current_a"
                    ),
                }
            )
        records.append(record)

    failed = [record for record in records if record["status"] != "pass"]
    result = {
        "schema_version": 1,
        "status": "pass" if not failed and not execution_errors else "fail",
        "scope": "partial trim-matrix execution; not a full calibration result",
        "view": args.view,
        "gds_sha256": gds_sha,
        "netlist_sha256": netlist_sha,
        "channels": channels,
        "codes": codes,
        "case_count": len(cases),
        "passing_case_count": len(records) - len(failed),
        "reused_case_count": len(reused),
        "rerun_case_count": len(pending),
        "execution_errors": execution_errors,
        "cases_detail": records,
    }
    output = BUILD / args.view / "shards" / shard_label(channels, codes) / "summary.json"
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(result, indent=2, sort_keys=True) + "\n")
    print(json.dumps(result, indent=2, sort_keys=True))
    print(f"report={output}")
    return 0 if result["status"] == "pass" else 1


if __name__ == "__main__":
    raise SystemExit(main())
