#!/usr/bin/env python3
"""Generate deterministic Magic placement input from the circuit manifest."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "layout" / "circuit.json"
OUTPUT = ROOT / "build" / "layout" / "place.tcl"


def fmt(value: float) -> str:
    return f"{value:.9g}"


def pcell_command(device: dict[str, object]) -> str:
    name = str(device["name"])
    kind = str(device["kind"])
    x = fmt(float(device["x"]))
    y = fmt(float(device["y"]))
    lines = [f"box {x}um {y}um {x}um {y}um"]

    if kind in {"nmos", "pmos"}:
        nf = int(device["nf"])
        if nf % 2 != 1:
            raise ValueError(f"{name}: MOS nf must be odd so both outer diffusions are ports")
        finger_w = float(device["total_w"]) / nf
        if finger_w < 0.42:
            raise ValueError(f"{name}: per-finger width {finger_w} is below SKY130 minimum")
        primitive = "nfet_01v8" if kind == "nmos" else "pfet_01v8"
        lines.append(
            f"magic::gencell sky130::sky130_fd_pr__{primitive} {name} "
            f"w {fmt(finger_w)} l {fmt(float(device['l']))} nf {nf} m 1 "
            "guard 1 conn_gates 1 full_metal 1 doports 1"
        )
    elif kind in {"res_high_po", "res_xhigh_po"}:
        primitive = (
            "res_high_po_1p41" if kind == "res_high_po" else "res_xhigh_po_1p41"
        )
        lines.append(
            f"magic::gencell sky130::sky130_fd_pr__{primitive} {name} "
            f"w 1.41 l {fmt(float(device['l']))} m 1 guard 1 full_metal 1 doports 1"
        )
    elif kind == "cap_mim_m3":
        lines.append(
            f"magic::gencell sky130::sky130_fd_pr__cap_mim_m3_1 {name} "
            f"w {fmt(float(device['w']))} l {fmt(float(device['l']))} "
            "nx 1 ny 1 doports 1"
        )
    else:
        raise ValueError(f"{name}: unsupported device kind {kind}")
    return "\n".join(lines)


def main() -> None:
    manifest = json.loads(MANIFEST.read_text())
    top = manifest["top"]
    commands = "\n\n".join(pcell_command(device) for device in manifest["devices"])
    script = f"""# Generated by tools/generate_layout_scripts.py; do not edit.
set PROJECT_ROOT [pwd]
set WORKDIR $PROJECT_ROOT/build/layout/buffered
file mkdir $WORKDIR
cd $WORKDIR

def read $PROJECT_ROOT/build/layout/tt_analog_1x2.def
cellname rename tt_um_template {top}

set POWER_STRIPE_WIDTH 2um
proc draw_power_stripe {{name x}} {{
    global POWER_STRIPE_WIDTH
    box $x 5um $x 220.76um
    box width $POWER_STRIPE_WIDTH
    paint met4
    # The compact label syntax accepts a '-' layer prefix as the sticky-pin
    # flag.  (With a vector font, Magic requires all font/rotation/offset
    # arguments before the layer name.)
    label $name center -met4
    port make
    port use [expr {{$name eq "VGND" ? "ground" : "power"}}]
    port class bidirectional
    port connections n s e w
}}
draw_power_stripe VDPWR 1um
draw_power_stripe VGND 4um

{commands}

save {top}.mag
writeall force
select top cell
expand
drc euclidean on
drc style drc(full)
drc check
puts "PLACEMENT_DRC_COUNT=[drc list count total]"
quit -noprompt
"""
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(script)
    print(f"Generated {OUTPUT} for {len(manifest['devices'])} devices")


if __name__ == "__main__":
    main()
